import { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { sha256Hex, uploadWithDescriptor, type UploadDescriptor } from './upload-contract';
import './styles.css';

type Extraction = {field:string; value:string|number; confidence:number; source:string; method?:string};
type Document = {id:string; filename:string; state:string; size:number; created_at:string; extraction?:Extraction[]; rejection_reason?:string; declared_sha256?:string};
type Audit = {id:string;event:string;actor:string;at:string;detail:Record<string,unknown>};
const API = import.meta.env.VITE_API_URL ?? '';
const AUTH_MODE = import.meta.env.VITE_AUTH_MODE ?? (window.location.hostname === 'localhost' || window.location.hostname === '127.0.0.1' ? 'disabled' : 'pkce');
const STATES = ['UPLOADED','SCANNING','OCR','EXTRACTING','NEEDS_REVIEW','APPROVED'];

function base64url(bytes: ArrayBuffer) { return btoa(String.fromCharCode(...new Uint8Array(bytes))).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,''); }
function headers(token: string): Record<string,string> { return token ? {Authorization:`Bearer ${token}`} : {}; }
function jwtPayload(token: string): Record<string, unknown> { try { return JSON.parse(atob(token.split('.')[1].replace(/-/g,'+').replace(/_/g,'/'))); } catch { return {}; } }

function App() {
  const [token,setToken] = useState(sessionStorage.getItem('sdi-token') ?? '');
  const [document,setDocument] = useState<Document|null>(null); const [audit,setAudit] = useState<Audit[]>([]);
  const [busy,setBusy] = useState(false); const [error,setError] = useState(''); const [comment,setComment] = useState('');
  const [corrections,setCorrections] = useState<Record<string,string>>({}); const [progress,setProgress] = useState('Ready for a bounded upload.');
  const signedIn = AUTH_MODE === 'disabled' || Boolean(token);
  const reviewable = document?.state === 'NEEDS_REVIEW' || document?.state === 'APPROVED';

  useEffect(() => { const params = new URLSearchParams(location.search); const code = params.get('code'); if (!code || AUTH_MODE !== 'pkce') return;
    const verifier = sessionStorage.getItem('sdi-verifier'); const redirect = `${location.origin}${location.pathname}`;
    if (!verifier) return; fetch(`${import.meta.env.VITE_COGNITO_DOMAIN}/oauth2/token`, {method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams({grant_type:'authorization_code',client_id:import.meta.env.VITE_COGNITO_CLIENT_ID,code,redirect_uri:redirect,code_verifier:verifier})}).then(r=>r.json()).then(data=>{ const idToken = data.id_token; const claims = typeof idToken === 'string' ? jwtPayload(idToken) : {}; if(idToken && claims.aud === import.meta.env.VITE_COGNITO_CLIENT_ID){sessionStorage.setItem('sdi-token',idToken);setToken(idToken);history.replaceState({},'',location.pathname);} else setError('Sign-in returned no Cognito ID token for this application.'); }).catch(()=>setError('Sign-in callback could not be completed.')); }, []);

  async function signIn() { const verifier = base64url(crypto.getRandomValues(new Uint8Array(32)).buffer); const challenge = base64url(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(verifier))); sessionStorage.setItem('sdi-verifier',verifier); const redirect=`${location.origin}${location.pathname}`; const query=new URLSearchParams({response_type:'code',client_id:import.meta.env.VITE_COGNITO_CLIENT_ID,redirect_uri:redirect,scope:'openid email',code_challenge_method:'S256',code_challenge:challenge}); location.assign(`${import.meta.env.VITE_COGNITO_DOMAIN}/oauth2/authorize?${query}`); }
  async function api(path:string, init:RequestInit = {}) { const requestHeaders:Record<string,string>={...headers(token)}; if(init.headers instanceof Headers) init.headers.forEach((value,key)=>requestHeaders[key]=value); else if(Array.isArray(init.headers)) init.headers.forEach(([key,value])=>requestHeaders[key]=value); else Object.assign(requestHeaders,init.headers ?? {}); const response = await fetch(`${API}${path}`, {...init, headers:requestHeaders}); if (!response.ok) { const detail = await response.json().catch(()=>({})); throw new Error(detail.detail ?? `Request failed (${response.status})`); } return response.status === 204 ? null : response.json(); }
  async function refresh(id = document?.id) { if(!id) return; const [doc,events,fields] = await Promise.all([api(`/v1/documents/${id}`),api(`/v1/documents/${id}/audit-events`),api(`/v1/documents/${id}/extractions`)]); setDocument({...doc,extraction:fields.items}); setAudit(events.events ?? []); }
  async function upload(file: File) { setBusy(true); setError(''); setProgress('Computing the declared SHA-256 digest…');
    try { const digest = await sha256Hex(file); setProgress('Creating an exact-size upload contract…'); const created=await api('/v1/uploads',{method:'POST',headers:{'content-type':'application/json','idempotency-key':`${file.name}-${file.size}-${file.lastModified}`},body:JSON.stringify({filename:file.name,content_type:file.type || 'text/plain',size:file.size,sha256:digest})}); setDocument(created.document); setProgress('Uploading to quarantine…'); const put=await uploadWithDescriptor(created.upload as UploadDescriptor,file,API,token); if(!put.ok) throw new Error('Bounded upload or digest verification failed'); setProgress('Queued for malware screening and extraction…'); await api(`/v1/documents/${created.document.id}/process`,{method:'POST'}); await refresh(created.document.id); } catch(e) { setError(e instanceof Error ? e.message : 'Unexpected error'); setProgress('Upload stopped safely.'); } finally { setBusy(false); } }
  useEffect(() => { if(!document || !['UPLOADED','SCANNING','OCR','EXTRACTING'].includes(document.state)) return; const timer=window.setInterval(()=>refresh(),1200); return()=>window.clearInterval(timer); }, [document?.id,document?.state]);
  async function review(decision:'APPROVED'|'REJECTED') { if(!document) return; setBusy(true); try { await api(`/v1/documents/${document.id}/reviews`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({reviewer:'web-reviewer',decision,comment,corrections:Object.fromEntries(Object.entries(corrections).filter(([,value])=>value))})}); setProgress(decision==='APPROVED'?'Approved and promoted to clean storage.':'Rejected and retained for audit.'); await refresh(); } catch(e){setError(e instanceof Error?e.message:'Review failed');} finally{setBusy(false);} }
  async function remove() { if(!document || !window.confirm(`Delete ${document.filename}? This removes content and audit records.`)) return; setBusy(true); try { await api(`/v1/documents/${document.id}`,{method:'DELETE'}); setDocument(null); setAudit([]); setCorrections({}); setProgress('Deleted from local storage and audit index.'); } catch(e){setError(e instanceof Error?e.message:'Delete failed');} finally{setBusy(false);} }
  const timeline = useMemo(()=>STATES.map(state=>({state,active:document ? STATES.indexOf(state)<=STATES.indexOf(document.state) : false})),[document]);
  if(!signedIn) return <main><header><span className="eyebrow">SECURE DOCUMENT INTELLIGENCE</span><h1>Evidence before approval.</h1><p>Sign in with Cognito authorization-code PKCE to open the tenant-scoped review console.</p></header><button className="primary" onClick={signIn}>Sign in securely</button><footer>Cloud mode uses same-origin CloudFront/API Gateway routing. Tokens stay in this browser session.</footer></main>;
  return <main><header><div className="topline"><span className="eyebrow">SECURE DOCUMENT INTELLIGENCE</span>{AUTH_MODE==='disabled'?<span className="mode">LOCAL · AUTH DISABLED</span>:<button className="link" onClick={()=>{sessionStorage.clear();setToken('');}}>Sign out</button>}</div><h1>Evidence before approval.</h1><p>Quarantine first. Every extracted value keeps a source citation and confidence score so a reviewer can make a bounded decision.</p></header>
    <section className="drop" aria-label="Upload document"><label htmlFor="file"><span className="upload-title">{busy ? progress : 'Choose a PDF, image, or text document'}</span><span className="upload-subtitle">Browser-computed SHA-256 · exact byte count · 10 MB maximum</span><input id="file" type="file" accept="application/pdf,image/png,image/jpeg,text/plain" disabled={busy} onChange={e=>e.target.files?.[0]&&upload(e.target.files[0])}/></label></section>
    {error&&<div className="error" role="alert">{error}</div>}
    {document&&<section className="card" aria-live="polite"><div className="row"><div><span className="eyebrow">DOCUMENT</span><h2>{document.filename}</h2><small>{document.size.toLocaleString()} bytes · tenant-scoped</small></div><span className={`state state-${document.state.toLowerCase()}`}>{document.state}</span></div>
      <ol className="timeline" aria-label="Processing progress">{timeline.map(item=><li className={item.active?'active':''} key={item.state}><span>{item.state}</span></li>)}</ol>
      {document.rejection_reason&&<p className="warning">{document.rejection_reason}</p>}{(document.state==='REJECTED'||document.state==='FAILED')&&<p className="warning">Processing stopped at a security boundary. Review the audit trail before retrying.</p>}
      <h3>Extracted fields</h3>{document.extraction?.length?<div className="fields">{document.extraction.map(item=><article key={item.field}><div className="field-head"><strong>{item.field}</strong><span className="confidence">{Math.round(item.confidence*100)}%</span></div><span className="value">{String(item.value)}</span>{reviewable&&<input aria-label={`Correction for ${item.field}`} value={corrections[item.field]??''} onChange={e=>setCorrections({...corrections,[item.field]:e.target.value})} placeholder="Human correction"/>}<small><b>Source:</b> {item.source}</small></article>)}</div>:<p className="muted">No fields extracted yet. The worker is still processing or the document requires review.</p>}
      <div className="actions">{reviewable&&<><textarea aria-label="Review comment" value={comment} onChange={e=>setComment(e.target.value)} maxLength={2000} placeholder="Review comment (optional)"/><button className="primary" disabled={busy} onClick={()=>review('APPROVED')}>Approve & promote</button><button className="secondary" disabled={busy} onClick={()=>review('REJECTED')}>Reject</button></>}<button className="danger" disabled={busy} onClick={remove}>Delete document</button></div>
      <h3>Audit trail</h3><ol className="audit">{audit.map(event=><li key={event.id}><strong>{event.event}</strong><span>{event.actor} · {new Date(event.at).toLocaleString()}</span></li>)}</ol></section>}
    <footer>Local mode uses deterministic adapters and disables authentication only on localhost. Cloud mode requires Cognito PKCE; malware and instruction-like content never bypass human review.</footer></main>;
}
createRoot(document.getElementById('root')!).render(<App/>);
